name: Data Pipeline CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint-and-test:
    name: "Lint & Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install dbt-core dbt-duckdb sqlfluff

      - name: dbt seed
        run: dbt seed --profiles-dir ./ci --target ci

      - name: dbt run
        run: dbt run --profiles-dir ./ci --target ci

      - name: dbt test
        run: dbt test --profiles-dir ./ci --target ci

      - name: SQLFluff lint
        continue-on-error: true
        run: sqlfluff lint models/ --dialect duckdb --ignore parsing